new_columns = {
    'property_offences_total_category': [
        'property_thefts_total',
        'property_aggravated_thefts_total',
        'property_petty_thefts_total',
        'property_receiving_stolen_offence_total',
        'property_aggravated_receiving_stolen_offence_total',
        'property_professional_receiving_stolen_total',
        'property_unauthorized_use_total',
        'property_aggravated_unauthorized_use_total',
        'property_theft_using_motor_vehicle_total',
        'property_aggravated_theft_using_motor_vehicle_total',
        'property_robbery',
        'property_preparation_aggravated_robbery_total',
        'property_extortion_total',
        'property_damage_total',
        'property_aggravated_damage_total',
        'property_embezzlement_total',
        'property_aggravate_embezzlement_total',
        'property_malicious_damage_data_total',
        'property_aggravated_malicious_damage_data_total',
        'property_fraud_total',
        'property_aggravated_fraud_total',
        'property_means_payment_fraud_total',
        'property_aggravated_means_payment_fraud_total',
        'property_tax_fraud_total',
        'property_aggravated_tax_fraud_total',
        'property_tax_infraction_total',
        'property_accounting_offence_total',
        'property_offences_trade_total',
        'property_forgery_total',
        'property_aggravated_forgery_total',
        'property_fraud_debtor_total',
        'property_infraction_debtor_total',
        'property_smuggling_total',
        'property_other_offences_total'
    ],

    'life_offences_total_category': [
        'life_manslaughter_total',
        'life_murder_total',
        'life_killing_total',
        'life_infanticide_total',
        'life_negligent_homicide_total'
    ],

    'health_offences_total_category': [
        'health_attempted_manslaughter_murder_killing_total',
        'health_assault_total',
        'health_aggravated_assault_total',
        'health_petty_assault_total',
        'health_preparation_aggravated_crime_total',
        'health_negligent_injury_total',
        'health_other_offences_total'
    ],

    'sexual_crimes_total_category': [
        'sexual_abuse_child_total',
        'sexual_rape_total',
        'sexual_other_offences_total'
    ],

    'authority_related_offences_total_category': [
        'authority_violent_resisting_official_total',
        'authority_impeding_official_total',
        'authority_perjury_total',
        'authority_perjury_proceedings_public_authority_total',
        'authority_giving_false_personal_data_total',
        'authority_other_crimes_against_public_authority_and_peace_total'
    ],

    'traffic_offences_total_category': [
        'traffic_aggravated_endangerment_total',
        'traffic_drunken_driving_total',
        'traffic_aggravated_drunken_driving_total',
        'traffic_waterway_air_rail_traffic_drunkenness_total',
        'traffic_relinquishing_vehicle_drunken_person_total',
        'traffic_drunken_driving_unpowered_vehicle_total',
        'traffic_unlawful_driving_vehicle_total',
        'traffic_endangerment_traffic_safety_hit_run_total',
        'traffic_infractions_total'
    ],

    'narcotic_offences_total_category': [
        'narcotics_offences_total',
        'narcotics_aggravated_offences_total',
        'narcotics_preparation_offence_total',
        'narcotics_abetment_offence_total',
        'narcotics_abuse_offence_total'
    ],

    'alcohol_offences_total_category': [
        'alcohol_minor_offence_total',
        'alcohol_offence_total',
        'alcohol_aggravated_offence_total',
        'alcohol_petty_offence_total'
    ],

    'investigations_total_category': [
        'investigation_suicide_investigation_total',
        'investigation_inquest_total',
        'investigation_missing_persons_total',
        'investigation_deer_collisions_total',
        'investigation_other_accident_investigation_total',
        'investigation_fire_investigation_total',
        'investigation_investigation_issuing_business_prohibition_total',
        'investigation_investigation_extradition_proceedings_of_offender_total'
    ],

    'other_offences_total_category': [
        'other_misclassified_offences_total',
        'other_restraining_order_matter',
        'other_persons_drowned_total',
        'other_persons_custody_intoxication_total',
        'other_violation_privacy_peace_honour_total',
        'other_criminal_mischief_total',
        'other_attempted_criminal_mischief_total',
        'other_offences_against_chaps_total',
        'other_military_offences_total',
        'other_labour_offences_total',
        'other_environmental_offences_total',
        'other_violation_intangible_rights_total',
        'other_offences_office_government_employees_total',
        'other_other_offences_against_penal_code_total',
        'other_public_meeting_order_keeping_infraction_total',
        'other_violation_industrial_safety_act_total',
        'other_public_order_violation_total',
        'other_offences_against_other_acts_decrees_total'
    ]
}

rename_columns = {
    'theft___281_all_offences':	'property_thefts_total',
    'aggravated_theft_282_all_offences': 'property_aggravated_thefts_total',
    'petty_theft_283_all_offences':	'property_petty_thefts_total',
    'receiving_stolen_property_offence_etc_321456910_all_offences':	'property_receiving_stolen_offence_total',
    'aggravated_receiving_stolen_property_offence_322_all_offences': 'property_aggravated_receiving_stolen_offence_total',
    'professional_receiving_stolen_property_offence_323_all_offences': 'property_professional_receiving_stolen_total',
    'unauthorised_use_etc_2879_all_offences': 'property_unauthorized_use_total',
    'aggravated_unauthorized_use_288_all_offences': 'property_aggravated_unauthorized_use_total',
    'theft_of_use_of_a_motor_vehicle_etc_289a9c_all_offences': 'property_theft_using_motor_vehicle_total',
    'aggravated_theft_of_use_of_a_motor_vehic_289b34a_all_offences': 'property_aggravated_theft_using_motor_vehicle_total',
    'robbery_311_all_offences': 'property_robbery',
    'aggravated_robbery_preparation_of_aggravated_robbery_312_2a_all_offences':	'property_preparation_aggravated_robbery_total',
    'extortion_aggravated_extortion_3134_all_offences':	'property_extortion_total',
    'damage_to_property_petty_damage_to_property_3513_all_offences': 'property_damage_total',
    'aggravated_damage_to_property_35234a_all_offences': 'property_aggravated_damage_total',
    'embezzlement_petty_embezzlement_2846_all_offences': 'property_embezzlement_total',
    'aggravated_embezzlement_285_all_offences':	'property_aggravate_embezzlement_total',
    'malicious_damage_to_data_petty_malicious_damage_to_data_353a_353c_all_offences': 'property_malicious_damage_data_total',
    'aggravated_malicious_damage_to_data_all_offences':	'property_aggravated_malicious_damage_data_total',
    'fraud_petty_fraud_3613_all_offences': 'property_fraud_total',
    'aggravated_fraud_362_all_offences': 'property_aggravated_fraud_total',
    'means_of_payment_fraud_petty_means_of_payment_fraud_preparation_thereof_3781011_all_offences':	'property_means_payment_fraud_total',
    'aggravated_means_of_payment_fraud_379_all_offences': 'property_aggravated_means_payment_fraud_total',
    'tax_fraud_petty_tax_fraud_2913_all_offences': 'property_tax_fraud_total',
    'aggravated_tax_fraud_292_all_offences': 'property_aggravated_tax_fraud_total',
    'tax_infraction_294_all_offences': 'property_tax_infraction_total',
    'accounting_offence_3099a10_all_offences': 'property_accounting_offence_total',
    'other_offences_in_trade_301810a_all_offences': 'property_offences_trade_total',
    'forgery_petty_forgery_possession_of_forgery_materials_33134_all_offences': 'property_forgery_total',
    'aggravated_forgery_332_all_offences': 'property_aggravated_forgery_total',
    'dishonesty_fraud_by_a_debtor_3913_all_offences': 'property_fraud_debtor_total',
    'deceitfulness_infraction_by_a_debtor_39456_all_offences': 'property_infraction_debtor_total',
    'smuggling_petty_smuggling_4645_all_offences': 'property_smuggling_total',
    'other_offences_against_property_281012a294a4b_5833536473717461366a_all_offences': 'property_other_offences_total',
    'manslaughter_211_34a_all_offences': 'life_manslaughter_total',
    'murder_212_34a_all_offences': 'life_murder_total',
    'killing_213_34a_all_offences': 'life_killing_total',
    'infanticide_214_all_offences': 'life_infanticide_total',
    'negligent_homicide_grossly_negligent_homicide_2189_all_offences': 'life_negligent_homicide_total',
    'attempted_manslaughter_murder_or_killing_2113_all_offences': 'health_attempted_manslaughter_murder_killing_total',
    'assault_215_all_offences': 'health_assault_total',
    'aggravated_assault_216_all_offences': 'health_aggravated_assault_total',
    'petty_assault_217_all_offences': 'health_petty_assault_total',
    'preparation_of_aggravated_crime_against_life_or_health_216a_all_offences': 'health_preparation_aggravated_crime_total',
    'negligent_injury_grossly_negligent_injury_211011_all_offences': 'health_negligent_injury_total',
    'other_offences_against_life_and_health_211215_225634a_all_offences': 'health_other_offences_total',
    'sexual_abuse_of_a_child_2067_all_offences': 'sexual_abuse_child_total',
    'rape_2012_all_offences': 'sexual_rape_total',
    'other_sexual_offences_2045_89_all_offences': 'sexual_other_offences_total',
    'violent_resisting_of_an_official_1612_all_offences': 'authority_violent_resisting_official_total',
    'impeding_of_an_official_163_all_offences': 'authority_impeding_official_total',
    'perjury_151_34_all_offences': 'authority_perjury_total',
    'perjury_at_the_proceedings_of_a_public_authority_152_all_offences': 'authority_perjury_proceedings_public_authority_total',
    'giving_of_false_personal_data_165_all_offences': 'authority_giving_false_personal_data_total',
    'other_crimes_against_public_authority_and_public_peace_155111644a6171734a_all_offences': 'authority_other_crimes_against_public_authority_and_peace_total',
    'aggravated_endangerment_of_traffic_232_all_offences': 'traffic_aggravated_endangerment_total',
    'drunken_driving_233_all_offences': 'traffic_drunken_driving_total',
    'aggravated_drunken_driving_234_all_offences': 'traffic_aggravated_drunken_driving_total',
    'waterway_air_or_rail_traffic_drunkenness_2357_all_offences': 'traffic_waterway_air_rail_traffic_drunkenness_total',
    'relinquishing_a_vehicle_to_a_drunken_person_238_all_offences': 'traffic_relinquishing_vehicle_drunken_person_total',
    'drunken_driving_of_an_unpowered_vehicle_239_all_offences': 'traffic_drunken_driving_unpowered_vehicle_total',
    'unlawful_driving_of_a_vehicle_2310_all_offences': 'traffic_unlawful_driving_vehicle_total',
    'endangerment_of_traffic_safety_hitandrun_23111_all_offences': 'traffic_endangerment_traffic_safety_hit_run_total',
    'traffic_infraction_violation_of_social_welfare_legislation_on_road_traffic_all_offences': 'traffic_infractions_total',
    'narcotics_offences_501_all_offences': 'narcotics_offences_total',
    'aggravated_narcotics_offence_502_all_offences': 'narcotics_aggravated_offences_total',
    'preparation_of_a_narcotics_offence_503_all_offences': 'narcotics_preparation_offence_total',
    'abetment_of_a_narcotics_offence_504_all_offences': 'narcotics_abetment_offence_total',
    'narcotics_abuse_offence_502a_all_offences': 'narcotics_abuse_offence_total',
    'minor_alcohol_offence_alcohol_act_all_offences': 'alcohol_minor_offence_total',
    'alcohol_offence__50a1_all_offences': 'alcohol_offence_total',
    'aggravated_alcohol_offence_50a2_all_offences': 'alcohol_aggravated_offence_total',
    'petty_alcohol_offence_50a3_all_offences': 'alcohol_petty_offence_total',
    'suicide_investigation_all_offences': 'investigation_suicide_investigation_total',
    'other_inquest_all_offences': 'investigation_inquest_total',
    'missing_persons_all_offences': 'investigation_missing_persons_total',
    'deer_collisions_all_offences': 'investigation_deer_collisions_total',
    'other_accident_investigation_all_offences': 'investigation_other_accident_investigation_total',
    'fire_investigation_all_offences': 'investigation_fire_investigation_total',
    'investigation_to_issuing_a_business_prohibition_all_offences': 'investigation_investigation_issuing_business_prohibition_total',
    'investigation_of_extradition_proceedings_of_an_offender_all_offences': 'investigation_investigation_extradition_proceedings_of_offender_total',
    'report_on_an_offence_evidently_not_to_be_included_in_the_statistics_as_an_offence_all_offences': 'other_misclassified_offences_total',
    'restraining_order_matter_all_offences': 'other_restraining_order_matter',
    'persons_drowned_all_offences': 'other_persons_drowned_total',
    'persons_taken_into_custody_due_to_intoxication_all_offences': 'other_persons_custody_intoxication_total',
    'violation_of_privacy_peace_and_honour_2434a_all_offences': 'other_violation_privacy_peace_honour_total',
    'criminal_mischief_criminal_traffic_mischief_341334a_all_offences': 'other_criminal_mischief_total',
    'attempted_criminal_mischief_criminal_traffic_mischief_341334a_all_offences': 'other_attempted_criminal_mischief_total',
    'offences_against_chaps_41_and_44_of_the_penal_code_all_offences': 'other_offences_against_chaps_total',
    'military_offences_45_all_offences': 'other_military_offences_total',
    'labour_offences_47_all_offences': 'other_labour_offences_total',
    'environmental_offences_48_all_offences': 'other_environmental_offences_total',
    'violation_of_certain_intangible_rights_49_all_offences': 'other_violation_intangible_rights_total',
    'offences_in_office_and_offences_by_general_government_employees_40_all_offences': 'other_offences_office_government_employees_total',
    'other_offences_against_the_penal_code_1114182311a253441134a3848a51_all_offences': 'other_other_offences_against_penal_code_total',
    'public_meeting_infraction_public_order_keeping_infraction_all_offences': 'other_public_meeting_order_keeping_infraction_total',
    'violation_of_the_industrial_safety_act_all_offences': 'other_violation_industrial_safety_act_total',
    'public_order_violation_all_offences': 'other_public_order_violation_total',
    'offences_against_other_acts_and_decrees_all_offences': 'other_offences_against_other_acts_decrees_total'
}

keep_columns = [
    'when',
    'where',
    'theft___281_all_offences',
    'aggravated_theft_282_all_offences',
    'petty_theft_283_all_offences',
    'receiving_stolen_property_offence_etc_321456910_all_offences',
    'aggravated_receiving_stolen_property_offence_322_all_offences',
    'professional_receiving_stolen_property_offence_323_all_offences',
    'unauthorised_use_etc_2879_all_offences',
    'aggravated_unauthorized_use_288_all_offences',
    'theft_of_use_of_a_motor_vehicle_etc_289a9c_all_offences',
    'aggravated_theft_of_use_of_a_motor_vehic_289b34a_all_offences',
    'robbery_311_all_offences',
    'aggravated_robbery_preparation_of_aggravated_robbery_312_2a_all_offences',
    'extortion_aggravated_extortion_3134_all_offences',
    'damage_to_property_petty_damage_to_property_3513_all_offences',
    'aggravated_damage_to_property_35234a_all_offences',
    'embezzlement_petty_embezzlement_2846_all_offences',
    'aggravated_embezzlement_285_all_offences',
    'malicious_damage_to_data_petty_malicious_damage_to_data_353a_353c_all_offences',
    'aggravated_malicious_damage_to_data_all_offences',
    'fraud_petty_fraud_3613_all_offences',
    'aggravated_fraud_362_all_offences',
    'means_of_payment_fraud_petty_means_of_payment_fraud_preparation_thereof_3781011_all_offences',
    'aggravated_means_of_payment_fraud_379_all_offences',
    'tax_fraud_petty_tax_fraud_2913_all_offences',
    'aggravated_tax_fraud_292_all_offences',
    'tax_infraction_294_all_offences',
    'accounting_offence_3099a10_all_offences',
    'other_offences_in_trade_301810a_all_offences',
    'forgery_petty_forgery_possession_of_forgery_materials_33134_all_offences',
    'aggravated_forgery_332_all_offences',
    'dishonesty_fraud_by_a_debtor_3913_all_offences',
    'deceitfulness_infraction_by_a_debtor_39456_all_offences',
    'smuggling_petty_smuggling_4645_all_offences',
    'other_offences_against_property_281012a294a4b_5833536473717461366a_all_offences',
    'manslaughter_211_34a_all_offences',
    'murder_212_34a_all_offences',
    'killing_213_34a_all_offences',
    'infanticide_214_all_offences',
    'negligent_homicide_grossly_negligent_homicide_2189_all_offences',
    'attempted_manslaughter_murder_or_killing_2113_all_offences',
    'assault_215_all_offences',
    'aggravated_assault_216_all_offences',
    'petty_assault_217_all_offences',
    'preparation_of_aggravated_crime_against_life_or_health_216a_all_offences',
    'negligent_injury_grossly_negligent_injury_211011_all_offences',
    'other_offences_against_life_and_health_211215_225634a_all_offences',
    'sexual_abuse_of_a_child_2067_all_offences',
    'rape_2012_all_offences',
    'other_sexual_offences_2045_89_all_offences',
    'violent_resisting_of_an_official_1612_all_offences',
    'impeding_of_an_official_163_all_offences',
    'perjury_151_34_all_offences',
    'perjury_at_the_proceedings_of_a_public_authority_152_all_offences',
    'giving_of_false_personal_data_165_all_offences',
    'other_crimes_against_public_authority_and_public_peace_155111644a6171734a_all_offences',
    'aggravated_endangerment_of_traffic_232_all_offences',
    'drunken_driving_233_all_offences',
    'aggravated_drunken_driving_234_all_offences',
    'waterway_air_or_rail_traffic_drunkenness_2357_all_offences',
    'relinquishing_a_vehicle_to_a_drunken_person_238_all_offences',
    'drunken_driving_of_an_unpowered_vehicle_239_all_offences',
    'unlawful_driving_of_a_vehicle_2310_all_offences',
    'endangerment_of_traffic_safety_hitandrun_23111_all_offences',
    'traffic_infraction_violation_of_social_welfare_legislation_on_road_traffic_all_offences',
    'narcotics_offences_501_all_offences',
    'aggravated_narcotics_offence_502_all_offences',
    'preparation_of_a_narcotics_offence_503_all_offences',
    'abetment_of_a_narcotics_offence_504_all_offences',
    'narcotics_abuse_offence_502a_all_offences',
    'minor_alcohol_offence_alcohol_act_all_offences',
    'alcohol_offence__50a1_all_offences',
    'aggravated_alcohol_offence_50a2_all_offences',
    'petty_alcohol_offence_50a3_all_offences',
    'suicide_investigation_all_offences',
    'other_inquest_all_offences',
    'missing_persons_all_offences',
    'deer_collisions_all_offences',
    'other_accident_investigation_all_offences',
    'fire_investigation_all_offences',
    'investigation_to_issuing_a_business_prohibition_all_offences',
    'investigation_of_extradition_proceedings_of_an_offender_all_offences',
    'report_on_an_offence_evidently_not_to_be_included_in_the_statistics_as_an_offence_all_offences',
    'restraining_order_matter_all_offences',
    'persons_drowned_all_offences',
    'persons_taken_into_custody_due_to_intoxication_all_offences',
    'violation_of_privacy_peace_and_honour_2434a_all_offences',
    'criminal_mischief_criminal_traffic_mischief_341334a_all_offences',
    'attempted_criminal_mischief_criminal_traffic_mischief_341334a_all_offences',
    'offences_against_chaps_41_and_44_of_the_penal_code_all_offences',
    'military_offences_45_all_offences',
    'labour_offences_47_all_offences',
    'environmental_offences_48_all_offences',
    'violation_of_certain_intangible_rights_49_all_offences',
    'offences_in_office_and_offences_by_general_government_employees_40_all_offences',
    'other_offences_against_the_penal_code_1114182311a253441134a3848a51_all_offences',
    'public_meeting_infraction_public_order_keeping_infraction_all_offences',
    'violation_of_the_industrial_safety_act_all_offences',
    'public_order_violation_all_offences',
    'offences_against_other_acts_and_decrees_all_offences'
]

ignore_columns = [
    'when',
    'where',
    'when_type',
    'where_type',
    'population',
    'year'
]

carryover_columns = [
    'when',
    'where',
    'when_type',
    'where_type',
    'population',
    'year'
]