# ToDo: Figure out the correct Finnish terms


CRIME_TYPES = {
    'property_offences': "omaisuusrikokset",
    'property_thefts_total': "varkausrikokset yhteensä",
    'property_aggravated_thefts_total': "törkeät varkaudet",
    'property_petty_thefts_total': "näpistykset",
    'property_receiving_stolen_offence_total': "kätkemisrikokset",
    'property_aggravated_receiving_stolen_offence_total': "törkeät kätkemisrikokset",
    'property_professional_receiving_stolen_total': "ammattimaiset kätkemisrikokset",
    'property_unauthorized_use_total': "luvattomat käytöt",
    'property_aggravated_unauthorized_use_total': "törkeät luvattomat käytöt",
    'property_theft_using_motor_vehicle_total': "moottorikulkuneuvon käyttövarkaudet",
    'property_aggravated_theft_using_motor_vehicle_total': "törkeät moottorikulkuneuvon käyttövarkaudet",
    'property_robbery': "ryöstöt",
    'property_preparation_aggravated_robbery_total': "törkeät ryöstöt",
    'property_extortion_total': "kiristykset",
    'property_damage_total': "vahingonteot",
    'property_aggravated_damage_total': "törkeät vahingonteot",
    'property_embezzlement_total': "kavallukset",
    'property_aggravate_embezzlement_total': "törkeät kavallukset",
    'property_malicious_damage_data_total': "datavahingonteot",
    'property_aggravated_malicious_damage_data_total': "törkeät datavahingonteot",
    'property_fraud_total': "petokset",
    'property_aggravated_fraud_total': "törkeät petokset",
    'property_means_payment_fraud_total': "maksuvälinepetokset",
    'property_aggravated_means_payment_fraud_total': "törkeät maksuvälinepetokset",
    'property_tax_fraud_total': "veropetokset",
    'property_aggravated_tax_fraud_total': "törkeät veropetokset",
    'property_tax_infraction_total': "verorikkomukset",
    'property_accounting_offence_total': "kirjanpitorikokset",
    'property_offences_trade_total': "muut elinkeinorikokset",
    'property_forgery_total': "väärennykset",
    'property_aggravated_forgery_total': "törkeät väärennykset",
    'property_fraud_debtor_total': "velallisen epärehellisyydet",
    'property_infraction_debtor_total': "velallisrikkomukset",
    'property_smuggling_total': "salakuljetukset",
    'property_other_offences_total': "muut omaisuusrikokset",
    'life_offences_total': "henkirikokset",
    'life_manslaughter_total': "tapot",
    'life_murder_total': "murhat",
    'life_killing_total': "surmat",
    'life_infanticide_total': "lapsensurmat",
    'life_negligent_homicide_total': "kuolemantuottamukset",
    'health_offences_total': "pahoinpitelyrikokset",
    'health_attempted_manslaughter_murder_killing_total': "tapon, murhan tai surman yritykset",
    'health_assault_total': "pahoinpitelyt",
    'health_aggravated_assault_total': "törkeät pahoinpitelyt",
    'health_petty_assault_total': "lievät pahoinpitelyt",
    'health_preparation_aggravated_crime_total': "törkeän henkeen tai terveyteen kohdistuvan rikoksen valmistelut",
    'health_negligent_injury_total': "vammantuottamukset",
    'health_other_offences_total': "muut henkeen ja terveyteen kohdistuneet rikokset",
    'sexual_crimes_total': "seksuaalirikokset",
    'sexual_abuse_child_total': "lapsen seksuaaliset hyväksikäytöt",
    'sexual_rape_total': "raiskaukset",
    'sexual_other_offences_total': "muut seksuaalirikokset",
    'authority_related_offences_total': "rikokset oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan",
    'authority_violent_resisting_official_total': "virkamiehen väkivaltaiset vastustamiset",
    'authority_impeding_official_total': "haitanteot virkamiehelle",
    'authority_perjury_total': "perättömät lausumat tuomioistuimessa",
    'authority_perjury_proceedings_public_authority_total': "perättömät lausumat viranomaismenettelyssä",
    'authority_giving_false_personal_data_total': "väärän henkilötiedon antamiset",
    'authority_other_crimes_against_public_authority_and_peace_total': "muut rikokset oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan",
    'traffic_offences_total': "liikennerikokset",
    'traffic_aggravated_endangerment_total': "törkeät liikenneturvallisuuden vaarantamiset",
    'traffic_drunken_driving_total': "rattijuopumukset",
    'traffic_aggravated_drunken_driving_total': "törkeät rattijuopumukset",
    'traffic_waterway_air_rail_traffic_drunkness_total': "vesi-, ilma- tai junaliikennejuopumukset",
    'traffic_relinquishing_vehicle_drunken_person_total': "kulkuneuvon luovuttamiset juopuneelle",
    'traffic_drunken_driving_unpowered_vehicle_total': "liikennejuopumukset moottorittomalla ajoneuvolla",
    'traffic_unlawful_driving_vehicle_total': "kulkuneuvon kuljettamiset oikeudetta",
    'traffic_endangerment_traffic_safety_hit_run_total': "liikenneturvallisuuden vaarantamiset ja liikennepaot",
    'traffic_infractions_total': "muut liikennerikkomukset",
    'narcotic_offences_total': "huumausainerikokset yhteensä",
    'narcotics_offences_total': "huumausainerikokset",
    'narcotics_aggravated_offences_total': "törkeät huumausainerikokset",
    'narcotics_preparation_offence_total': "huumausainerikokset valmistelut",
    'narcotics_abetment_offence_total': "huumausainerikoksen edistämiset",
    'narcotics_abuse_offence_total': "huumausaineen käyttörikokset",
    'alcohol_offences_total': "alkoholirikokset ja -rikkomukset yhteensä",
    'alcohol_minor_offence_total': "alkoholirikkomukset",
    'alcohol_offence_total': "alkoholirikokset",
    'alcohol_aggravated_offence_total': "törkeät alkoholirikokset",
    'alcohol_petty_offence_total': "lievät alkoholirikokset",
    'investigations_total': "tutkinnat yhteensä",
    'investigations_suicide_investigation_total': "itsemurhan tutkinnat",
    'investigations_inquest_total': "muut kuolemansyytutkimukset",
    'investigations_missing_persons_total': "kadonneet henkilöt",
    'investigations_deer_collisions_total': "hirvieläinkolarit",
    'investigations_other_accident_investigation_total': "muut onnettomuustutkinnat",
    'investigations_fire_investigation_total': "palosyyn tutkinnat",
    'investigations_investigation_issuing_business_prohibition_total': "tutkinnat liiketoimintakiellon määräämiseksi",
    'investigations_investigation_extradition_proceedings_of_offender_total': "tutkinnat rikoksentekijän luovutusmenettelyssä",
    'other_offences_total': "other offences",
    'other_misclassified_offences_total': "rikosilmoitukset, joita ei tilastoitane rikoksina",
    'other_restraining_order_matter_total': "lähestymiskieltoasiat",
    'other_persons_drowned_total': "hukkuneet henkilöt",
    'other_persons_custody_intoxication_total': "päihtymyksen takia säilöönotetut",
    'other_violation_privacy_peace_honour_total': "yksityisyyden, rauhan ja kunnian loukkaamiset",
    'other_criminal_mischief_total': "tuhotyöt",
    'other_attempted_criminal_mischief_total': "tuhotyön yritykset",
    'other_offences_against_chaps_total': "rikoslain lukujen 41 ja 44 rikokset",
    'other_military_offences_total': "sotilasrikokset",
    'other_labour_offences_total': "työrikokset",
    'other_environmental_offences_total': "ympäristörikokset",
    'other_violation_intangible_rights_total': "eräiden aineettomien oikeuksien loukkaamiset",
    'other_offences_office_government_employees_total': "virkarikokset ja julkisyhteisön työntekijän rikokset",
    'other_other_offences_against_penal_code_total': "muut rikoslakia vastaan tehdyt rikokset",
    'other_public_meeting_order_keeping_infraction_total': "kokoontumisrikkomukset",
    'other_violation_industrial_safety_act_total': "työturvallisuusrikkomukset",
    'other_public_order_violation_total': "järjestysrikkomukset",
    'other_offences_against_other_acts_decrees_total': "rikokset muita lakeja ja asetuksia vastaan",
}
