# ToDo: Figure out the correct Finnish terms


CRIME_TYPES = {
    'sg': {
        'property_offences_total_category': "omaisuusrikos",
        'property_thefts_total': "varkausrikos",
        'property_aggravated_thefts_total': "törkeä varkaus",
        'property_petty_thefts_total': "näpistys",
        'property_receiving_stolen_offence_total': "kätkemisrikos",
        'property_aggravated_receiving_stolen_offence_total': "törkeä kätkemisrikos",
        'property_professional_receiving_stolen_total': "ammattimainen kätkemisrikos",
        'property_unauthorized_use_total': "luvaton käyttö",
        'property_aggravated_unauthorized_use_total': "törkeä luvaton käyttö",
        'property_theft_using_motor_vehicle_total': ("moottorikulkuneuvon käyttövarkaus", [0]),
        'property_aggravated_theft_using_motor_vehicle_total': ("törkeä moottorikulkuneuvon käyttövarkaus", [1]),
        'property_robbery': "ryöstö",
        'property_preparation_aggravated_robbery_total': "törkeä ryöstö",
        'property_extortion_total': "kiristys",
        'property_damage_total': "vahingonteko",
        'property_aggravated_damage_total': "törkeä vahingonteko",
        'property_embezzlement_total': "kavallus",
        'property_aggravate_embezzlement_total': "törkeä kavallus",
        'property_malicious_damage_data_total': "datavahingonteko",
        'property_aggravated_malicious_damage_data_total': "törkeä datavahingonteko",
        'property_fraud_total': "petos",
        'property_aggravated_fraud_total': "törkeä petos",
        'property_means_payment_fraud_total': "maksuvälinepetos",
        'property_aggravated_means_payment_fraud_total': "törkeä maksuvälinepetos",
        'property_tax_fraud_total': "veropetos",
        'property_aggravated_tax_fraud_total': "törkeä veropetos",
        'property_tax_infraction_total': "verorikkomus",
        'property_accounting_offence_total': "kirjanpitorikos",
        'property_offences_trade_total': "muu elinkeinorikos",
        'property_forgery_total': "väärennys",
        'property_aggravated_forgery_total': "törkeä väärennys",
        'property_fraud_debtor_total': ("velallisen epärehellisyys",[0]),
        'property_infraction_debtor_total': "velallisrikkomus",
        'property_smuggling_total': "salakuljetus",
        'property_other_offences_total': "muu omaisuusrikos",
        'life_offences_total_category': "henkirikos",
        'life_manslaughter_total': "tappo",
        'life_murder_total': "murha",
        'life_killing_total': "surma",
        'life_infanticide_total': "lapsensurma",
        'life_negligent_homicide_total': "kuolemantuottamus",
        'health_offences_total_category': "pahoinpitelyrikos",
        'health_attempted_manslaughter_murder_killing_total': ("tapon, murhan tai surman yritys", [0, 1, 2, 3]),
        'health_assault_total': "pahoinpitely",
        'health_aggravated_assault_total': "törkeä pahoinpitely",
        'health_petty_assault_total': "lievä pahoinpitely",
        'health_preparation_aggravated_crime_total': ("törkeän henkeen tai terveyteen kohdistuvan rikoksen valmistelu", [1, 2, 3, 4, 5]),
        'health_negligent_injury_total': "vammantuottamus",
        'health_other_offences_total': ("muu henkeen ja terveyteen kohdistunut rikos", [1, 2, 3]),
        'sexual_crimes_total_category': "seksuaalirikos",
        'sexual_abuse_child_total': ("lapsen seksuaalinen hyväksikäyttö", [0]),
        'sexual_rape_total': "raiskaus",
        'sexual_other_offences_total': "muu seksuaalirikos",
        'authority_related_offences_total_category': ("oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan tehty rikos", [0, 1, 2, 3, 4, 5]),
        'authority_violent_resisting_official_total': ("virkamiehen väkivaltainen vastustaminen", [0]),
        'authority_impeding_official_total': ("haitanteko virkamiehelle", [1]),
        'authority_perjury_total': ("tuomioistuimessa annettu perätön lausuma", [0]),
        'authority_perjury_proceedings_public_authority_total': ("viranomaismenettelyssä annettu perätön lausuma", [0]),
        'authority_giving_false_personal_data_total': ("väärän henkilötiedon antaminen", [0, 1]),
        'authority_other_crimes_against_public_authority_and_peace_total': ("oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan tehty muu rikos", [0, 1, 2, 3, 4, 5]),
        'traffic_offences_total_category': "liikennerikos",
        'traffic_aggravated_endangerment_total': ("törkeä liikenneturvallisuuden vaarantaminen", [1]),
        'traffic_drunken_driving_total': "rattijuopumus",
        'traffic_aggravated_drunken_driving_total': "törkeä rattijuopumus",
        'traffic_waterway_air_rail_traffic_drunkness_total': ("vesi-, ilma- tai junaliikennejuopumus", [0, 1, 2]),
        'traffic_relinquishing_vehicle_drunken_person_total': ("kulkuneuvon luovuttaminen juopuneelle", [0, 2]),
        'traffic_drunken_driving_unpowered_vehicle_total': ("liikennejuopumus moottorittomalla ajoneuvolla", [1, 2]),
        'traffic_unlawful_driving_vehicle_total': ("kulkuneuvon oikeudetta kuljettaminen", [0, 1]),
        'traffic_endangerment_traffic_safety_hit_run_total': ("liikenneturvallisuuden vaarantaminen ja liikennepako", [0, 2]),
        'traffic_infractions_total': "muu liikennerikkomus",
        'narcotic_offences_total_category': "huumausainerikos",
        'narcotics_offences_total': "huumausainerikos",
        'narcotics_aggravated_offences_total': "törkeä huumausainerikos",
        'narcotics_preparation_offence_total': ("huumausainerikoksen valmistelu", [0]),
        'narcotics_abetment_offence_total': ("huumausainerikoksen edistäminen", [0]),
        'narcotics_abuse_offence_total': ("huumausaineen käyttörikos", [0]),
        'alcohol_offences_total_category': ("alkoholirikos ja -rikkomus", [1]),
        'alcohol_minor_offence_total': "alkoholirikkomus",
        'alcohol_offence_total': "alkoholirikos",
        'alcohol_aggravated_offence_total': "törkeä alkoholirikos",
        'alcohol_petty_offence_total': "lievä alkoholirikos",
        'investigation_total_category': "tutkinta",
        'investigation_suicide_investigation_total': ("itsemurhan tutkinta", [0]),
        'investigation_inquest_total': "muu kuolemansyytutkimus",
        'investigation_missing_persons_total': "kadonnut henkilö",
        'investigation_deer_collisions_total': "hirvieläinkolari",
        'investigation_other_accident_investigation_total': "muu onnettomuustutkinta",
        'investigation_fire_investigation_total': ("palosyyn tutkinta", [0]),
        'investigation_investigation_issuing_business_prohibition_total': ("liiketoimintakiellon määräämiseksi tehty tutkinta", [0, 1]),
        'investigation_investigation_extradition_proceedings_of_offender_total': ("rikoksentekijän luovutusmenettelyyn liittyvä tutkinta", [0, 1]),
        'other_offences_total_category': "muu rikkomus",
        'other_misclassified_offences_total': ("ei rikoksina tilastoitava rikosilmoitus", [0, 1]),
        'other_restraining_order_matter_total': "lähestymiskieltoasia",
        'other_persons_drowned_total': "hukkunut henkilö",
        'other_persons_custody_intoxication_total': ("päihtymyksen takia säilöönotettu", [0, 1]),
        'other_violation_privacy_peace_honour_total': ("yksityisyyden, rauhan ja kunnian loukkaaminen", [0, 1, 2, 3]),
        'other_criminal_mischief_total': "tuhotyö",
        'other_attempted_criminal_mischief_total': ("tuhotyön yritys", [0]),
        'other_offences_against_chaps_total': ("rikoslain lukujen 41 ja 44 rikos", [0, 1, 2, 3, 4]),
        'other_military_offences_total': "sotilasrikos",
        'other_labour_offences_total': "työrikos",
        'other_environmental_offences_total': "ympäristörikos",
        'other_violation_intangible_rights_total': ("eräiden aineettomien oikeuksien loukkaaminen", [0, 1, 2]),
        'other_offences_office_government_employees_total': ("virkarikos ja julkisyhteisön työntekijän rikos", [1, 2, 3]),
        'other_other_offences_against_penal_code_total': ("muu rikoslakia vastaan tehty rikos", [1, 2]),
        'other_public_meeting_order_keeping_infraction_total': "kokoontumisrikkomus",
        'other_violation_industrial_safety_act_total': "työturvallisuusrikkomus",
        'other_public_order_violation_total': "järjestysrikkomus",
        'other_offences_against_other_acts_decrees_total': ("muita lakeja ja asetuksia vastaan tehty rikos", [0, 1, 2, 3, 4]),
    },
    'pl': {
        'property_offences_total_category': "omaisuusrikokset",
        'property_thefts_total': "varkausrikokset",
        'property_aggravated_thefts_total': "törkeät varkaudet",
        'property_petty_thefts_total': "näpistykset",
        'property_receiving_stolen_offence_total': "kätkemisrikokset",
        'property_aggravated_receiving_stolen_offence_total': "törkeät kätkemisrikokset",
        'property_professional_receiving_stolen_total': "ammattimaiset kätkemisrikokset",
        'property_unauthorized_use_total': "luvattomat käytöt",
        'property_aggravated_unauthorized_use_total': "törkeät luvattomat käytöt",
        'property_theft_using_motor_vehicle_total': ("moottorikulkuneuvon käyttövarkaudet", [0]),
        'property_aggravated_theft_using_motor_vehicle_total': ("törkeät moottorikulkuneuvon käyttövarkaudet", [1]),
        'property_robbery': "ryöstöt",
        'property_preparation_aggravated_robbery_total': "törkeät ryöstöt",
        'property_extortion_total': "kiristykset",
        'property_damage_total': "vahingonteot",
        'property_aggravated_damage_total': "törkeät vahingonteot",
        'property_embezzlement_total': "kavallukset",
        'property_aggravate_embezzlement_total': "törkeät kavallukset",
        'property_malicious_damage_data_total': "datavahingonteot",
        'property_aggravated_malicious_damage_data_total': "törkeät datavahingonteot",
        'property_fraud_total': "petokset",
        'property_aggravated_fraud_total': "törkeät petokset",
        'property_means_payment_fraud_total': "maksuvälinepetokset",
        'property_aggravated_means_payment_fraud_total': "törkeät maksuvälinepetokset",
        'property_tax_fraud_total': "veropetokset",
        'property_aggravated_tax_fraud_total': "törkeät veropetokset",
        'property_tax_infraction_total': "verorikkomukset",
        'property_accounting_offence_total': "kirjanpitorikokset",
        'property_offences_trade_total': "muut elinkeinorikokset",
        'property_forgery_total': "väärennykset",
        'property_aggravated_forgery_total': "törkeät väärennykset",
        'property_fraud_debtor_total': ("velallisen epärehellisyydet",[0]),
        'property_infraction_debtor_total': "velallisrikkomukset",
        'property_smuggling_total': "salakuljetukset",
        'property_other_offences_total': "muut omaisuusrikokset",
        'life_offences_total_category': "henkirikokset",
        'life_manslaughter_total': "tapot",
        'life_murder_total': "murhat",
        'life_killing_total': "surmat",
        'life_infanticide_total': "lapsensurmat",
        'life_negligent_homicide_total': "kuolemantuottamukset",
        'health_offences_total_category': "pahoinpitelyrikokset",
        'health_attempted_manslaughter_murder_killing_total': ("tapon, murhan tai surman yritykset", [0, 1, 2, 3]),
        'health_assault_total': "pahoinpitelyt",
        'health_aggravated_assault_total': "törkeät pahoinpitelyt",
        'health_petty_assault_total': "lievät pahoinpitelyt",
        'health_preparation_aggravated_crime_total': ("törkeän henkeen tai terveyteen kohdistuvan rikoksen valmistelut", [1, 2, 3, 4, 5]),
        'health_negligent_injury_total': "vammantuottamukset",
        'health_other_offences_total': ("muut henkeen ja terveyteen kohdistuneet rikokset", [1, 2, 3]),
        'sexual_crimes_total_category': "seksuaalirikokset",
        'sexual_abuse_child_total': ("lapsen seksuaaliset hyväksikäytöt", [0]),
        'sexual_rape_total': "raiskaukset",
        'sexual_other_offences_total': "muut seksuaalirikokset",
        'authority_related_offences_total_category': ("oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan tehdyt rikokset", [0, 1, 2, 3, 4, 5]),
        'authority_violent_resisting_official_total': ("virkamiehen väkivaltaiset vastustamiset", [0]),
        'authority_impeding_official_total': ("haitanteot virkamiehelle", [1]),
        'authority_perjury_total': ("tuomioistuimessa annetut perättömät lausumat", [0]),
        'authority_perjury_proceedings_public_authority_total': ("viranomaismenettelyssä annetut perättömät lausumat", [0]),
        'authority_giving_false_personal_data_total': ("väärän henkilötiedon antamiset", [0, 1]),
        'authority_other_crimes_against_public_authority_and_peace_total': ("oikeudenkäyttöä, viranomaisia ja yleistä järjestystä vastaan tehdyt muut rikokset", [0, 1, 2, 3, 4, 5]),
        'traffic_offences_total_category': "liikennerikokset",
        'traffic_aggravated_endangerment_total': ("törkeät liikenneturvallisuuden vaarantamiset", [1]),
        'traffic_drunken_driving_total': "rattijuopumukset",
        'traffic_aggravated_drunken_driving_total': "törkeät rattijuopumukset",
        'traffic_waterway_air_rail_traffic_drunkness_total': ("vesi-, ilma- tai junaliikennejuopumukset", [0, 1, 2]),
        'traffic_relinquishing_vehicle_drunken_person_total': ("kulkuneuvon luovuttamiset juopuneelle", [0, 2]),
        'traffic_drunken_driving_unpowered_vehicle_total': ("liikennejuopumukset moottorittomalla ajoneuvolla", [1, 2]),
        'traffic_unlawful_driving_vehicle_total': ("kulkuneuvon oikeudetta kuljettamiset", [0, 1]),
        'traffic_endangerment_traffic_safety_hit_run_total': ("liikenneturvallisuuden vaarantamiset ja liikennepaot", [0, 2]),
        'traffic_infractions_total': "muut liikennerikkomukset",
        'narcotic_offences_total_category': "huumausainerikokset",
        'narcotics_offences_total': "huumausainerikokset",
        'narcotics_aggravated_offences_total': "törkeät huumausainerikokset",
        'narcotics_preparation_offence_total': ("huumausainerikoksen valmistelut", [0]),
        'narcotics_abetment_offence_total': ("huumausainerikoksen edistämiset", [0]),
        'narcotics_abuse_offence_total': ("huumausaineen käyttörikokset", [0]),
        'alcohol_offences_total_category': ("alkoholirikokset ja -rikkomukset", [1]),
        'alcohol_minor_offence_total': "alkoholirikkomukset",
        'alcohol_offence_total': "alkoholirikokset",
        'alcohol_aggravated_offence_total': "törkeät alkoholirikokset",
        'alcohol_petty_offence_total': "lievät alkoholirikokset",
        'investigation_total_category': "tutkinnat",
        'investigation_suicide_investigation_total': ("itsemurhan tutkinnat", [0]),
        'investigation_inquest_total': "muut kuolemansyytutkimukset",
        'investigation_missing_persons_total': "kadonneet henkilöt",
        'investigation_deer_collisions_total': "hirvieläinkolarit",
        'investigation_other_accident_investigation_total': "muut onnettomuustutkinnat",
        'investigation_fire_investigation_total': ("palosyyn tutkinnat", [0]),
        'investigation_investigation_issuing_business_prohibition_total': ("liiketoimintakiellon määräämiseksi tehdyt tutkinnat", [0, 1]),
        'investigation_investigation_extradition_proceedings_of_offender_total': ("rikoksentekijän luovutusmenettelyyn liittyvät tutkinnat", [0, 1]),
        'other_offences_total_category': "muut rikkomukset",
        'other_misclassified_offences_total': ("ei rikoksina tilastoitavat rikosilmoitukset", [0, 1]),
        'other_restraining_order_matter_total': "lähestymiskieltoasiat",
        'other_persons_drowned_total': "hukkuneet henkilöt",
        'other_persons_custody_intoxication_total': ("päihtymyksen takia säilöönotetut", [0, 1]),
        'other_violation_privacy_peace_honour_total': ("yksityisyyden, rauhan ja kunnian loukkaamiset", [0, 1, 2, 3]),
        'other_criminal_mischief_total': "tuhotyöt",
        'other_attempted_criminal_mischief_total': ("tuhotyön yritykset", [0]),
        'other_offences_against_chaps_total': ("rikoslain lukujen 41 ja 44 rikokset", [0, 1, 2, 3, 4]),
        'other_military_offences_total': "sotilasrikokset",
        'other_labour_offences_total': "työrikokset",
        'other_environmental_offences_total': "ympäristörikokset",
        'other_violation_intangible_rights_total': ("eräiden aineettomien oikeuksien loukkaamiset", [0, 1, 2]),
        'other_offences_office_government_employees_total': ("virkarikokset ja julkisyhteisön työntekijän rikokset", [1, 2, 3]),
        'other_other_offences_against_penal_code_total': ("muut rikoslakia vastaan tehdyt rikokset", [1, 2]),
        'other_public_meeting_order_keeping_infraction_total': "kokoontumisrikkomukset",
        'other_violation_industrial_safety_act_total': "työturvallisuusrikkomukset",
        'other_public_order_violation_total': "järjestysrikkomukset",
        'other_offences_against_other_acts_decrees_total': ("muita lakeja ja asetuksia vastaan tehdyt rikokset", [0, 1, 2, 3, 4]),
    }
}
